=== indadominguez/lmsgi-recetas-Indalecio_Dominguez/recetas.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="recetas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="receta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            
                            <xs:element name="categoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Entrante"/>
                                        <xs:enumeration value="Principal"/>
                                        <xs:enumeration value="Postre"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="tiempo" type="xs:integer"/>
                            <xs:element name="dificultad" type="xs:string"/>
                        </xs:sequence>

                        <xs:attribute name="codigo" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== indadominguez/lmsgi-recetas-Indalecio_Dominguez/recetas.xml
<recetas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="recetas.xsd">
    <receta>
        <nombre>Pizza</nombre>
        <categoria>Principal</categoria>
        <tiempo>30</tiempo>
        <dificultad>Media</dificultad>
    </receta>

    <receta>
        <nombre>Salmorejo</nombre>
        <categoria>Entrante</categoria>
        <tiempo>12</tiempo>
        <dificultad>Baja</dificultad>
    </receta>

    <receta>
        <nombre>Helado</nombre>
        <categoria>Postre</categoria>
        <tiempo>50</tiempo>
        <dificultad>Alta</dificultad>
    </receta>
</recetas>
